name: embedded-check

on:
  push:
jobs:

  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: insper-embarcados/actions-embedded-check@v2
        with:
          c_file: mqtt/mqtt_client.c
          rtos: false
